# Generated by Django 3.1.5 on 2021-02-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.SlugField(default=32, help_text='Введите ссылку', max_length=60, verbose_name='Ссылка теста'),
            preserve_default=False,
        ),
    ]
