# Generated by Django 3.1.5 on 2021-02-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        ('quiz', '0002_quiz_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.couesetable', verbose_name='Category'),
        ),
    ]
