# Generated by Django 3.1.5 on 2021-02-07 00:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210207_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='url',
        ),
        migrations.AlterField(
            model_name='progress',
            name='correct_answer',
            field=models.CharField(max_length=10, verbose_name='Правельные ответы'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='score',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='wrong_answer',
            field=models.CharField(max_length=10, verbose_name='Неправельные ответы'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='draft',
            field=models.BooleanField(blank=True, default=False, help_text='Если да, то тест не отображаетсяв списке викторин и может быть тольковзято пользователями, которые могут редактировать тест.', verbose_name='Проект'),
        ),
    ]
