# Generated by Django 3.1.5 on 2021-02-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210207_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Количество вопросов, на которые ужно ответить при каждой попытке.', null=True, verbose_name='Количество вопросов'),
        ),
    ]
