# Generated by Django 3.1.5 on 2021-02-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], help_text='Порядок, в котором множественном варианты ответа отображаются для пользователя', max_length=30, null=True, verbose_name='Порядок ответа'),
        ),
    ]
