# Generated by Django 3.2 on 2021-05-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Введите текст ответа, который                                             вы хотите показать', max_length=1000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Это правильный ответ?', verbose_name='Правильный'),
        ),
    ]
