# Generated by Django 3.1.4 on 2021-01-14 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoueseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Название курса')),
                ('task', models.TextField(max_length=250, verbose_name='Описание курса')),
                ('teache', models.CharField(max_length=50, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='RolesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Name', models.CharField(max_length=30, verbose_name='Имя')),
                ('Patromic', models.CharField(max_length=40, verbose_name='Отчество')),
                ('email', models.CharField(max_length=40, verbose_name='E-mail')),
                ('user_status', models.CharField(max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='TopicTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Название темы')),
                ('task', models.TextField(max_length=250, verbose_name='Описание темы')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.couesetable')),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='AssignedCoursesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.couesetable')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курс',
            },
        ),
    ]
