# Generated by Django 3.1.5 on 2021-04-29 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couesetable',
            name='users',
        ),
        migrations.AlterField(
            model_name='couesetable',
            name='teache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
