# Generated by Django 3.1.2 on 2020-11-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kursu',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='kursu',
            name='task',
            field=models.TextField(max_length=250, verbose_name='Описание курса'),
        ),
    ]
