# Generated by Django 3.1.2 on 2020-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_auto_20201127_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
