# Generated by Django 3.1.2 on 2020-11-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_addtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtopic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Тему'},
        ),
    ]
