# Generated by Django 3.1.2 on 2020-11-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_auto_20201129_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtopic',
            options={'verbose_name': 'Тему', 'verbose_name_plural': 'Темы'},
        ),
    ]
