# Generated by Django 3.1.4 on 2020-12-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_auto_20201129_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtopic',
            name='kursu_ptr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cours.kursu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtopic',
            name='task',
            field=models.TextField(default=123, max_length=250, verbose_name='Описание темы'),
            preserve_default=False,
        ),
    ]
