# Generated by Django 3.1.2 on 2020-12-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_auto_20201205_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Name', models.CharField(max_length=30, verbose_name='Имя')),
                ('Patromic', models.CharField(max_length=40, verbose_name='Отчество')),
                ('email', models.CharField(max_length=40, verbose_name='E-mail')),
                ('user_status', models.CharField(max_length=30, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedCoursesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.kursu')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.usertable')),
            ],
        ),
    ]
